name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: mydatabase
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Check out code
      uses: actions/checkout@v4  # Mise à jour vers la version compatible Node.js 20

    - name: Set up Python
      uses: actions/setup-python@v4  # Mise à jour vers la version compatible Node.js 20
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for MySQL to be ready
      run: sleep 15  # Attendre 15 secondes pour que MySQL soit prêt

    - name: Verify MySQL is running
      run: |
        mysqladmin -h localhost -u root -proot ping

    - name: Run MySQL setup
      env:
        MYSQL_DATABASE_URI: mysql+pymysql://root:root@localhost:3306/mydatabase
      run: |
        python migrations/mysql_setup.py

    - name: Run tests with pytest
      run: |
        pytest --maxfail=5 --disable-warnings
